### ISSUE TITLE
Logging configuration

### ISSUE THREAD

**Issue by r1chardj0n3s** [pypa/warehouse#107]
There's already some logging being done by the app - the web requests. There will be more logging done explicitly by code as users do things (dumb things _or_ good things).

I'm going to add a new section to the configuration file called logging which will have the following structure (closely mirroring the standard logging configuration file structure, but not requiring us to actually have a separate INI syntax file).

``` yaml
logging:
    formatters:
        simpleFormater:
            format: '%(asctime)s - %(levelname)s: %(message)s'
            datefmt: '%Y/%m/%d %H:%M:%S'

    handlers:
        console:
            class: logging.StreamHandler
            formatter: simpleFormater
            level: DEBUG
            stream: ext://sys.stdout
        file:
            class : logging.FileHandler
            formatter: simpleFormater
            level: WARNING
            filename: output.log

    loggers:
        clogger:
            level: DEBUG
            handlers: [console]
        flogger:
            level: WARNING
            handlers: [file]

    root:
        level: DEBUG
        handlers: [console, file]
```

This example is way more complex than I imagine any given configuration would actually be.

This configuration is then loaded with some code like:

``` python
# config = loaded yaml config
logging_conf = config['logging']
logging_conf.setdefault('version', 1)
logging.config.dictConfig(logging_conf)
```

For a more concrete dev configuration I anticipate something like:

``` yaml
logging:
    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            stream: ext://sys.stdout

    root:
        level: DEBUG
        handlers: [console]
```

(which will hopefully work; actual results may vary of course given it's the logging module we're talking about)
