### ISSUE TITLE
dark-overlay remains after window is resized larger than the breakpoint

### ISSUE THREAD

**Issue by sohail288** [pypa/warehouse#1775]
another issue that I found while messing around is that when you have the window sized small enough to show the "Add Filter" button, and then click it, and then resize the window to a larger size than the breakpoint (at 1000px currently), the screen remains unusable with no way of getting rid of the overlay.  You have to resize the window below 1000px and then click on the "close" button.

I believe it would be best to restructure the css code a bit, but currently, I can only come up with the following:

```
window.onresize = function () {
  if (window.screen.width > 1000) {
     document.querySelector('.-js-dark-overlay').style.display = '';
 	 document.querySelector('.-js-filter-panel').style.display= '';
  }
}
```

**Comment by emoreno911** [comment]
You can use a CSS Media Query like this one:

`@media (min-width: 1000px){
     .dark-overlay.-js-dark-overlay { display: none !important; }
}`

Or you can attach the sidebar's close handler to the click event on overlay too

**Comment by nlhkabu** [comment]
I might be wrong here, but I think our css linter prevents `!important` css calls (with good reason)

**Comment by emoreno911** [comment]
You're right, well that was the easy way. Another approach is to create a class for when the sidebar is open

```scss
.left-layout__sidebar.sidebar-open {
  .dark-overlay,
  .filter-panel { 
    display: block; 
  }
}

@media (min-width: 1000px){ 
  .left-layout__sidebar.sidebar-open {
    .dark-overlay{ 
      display: none; 
    }
  }
}
```

Then instead of use inline-styles to show/hide the elements just add/remove this(`.sidebar-open`) class in `.left-layout__sidebar`, with this you'll avoid to override the Specificity of the classes.
