### ISSUE TITLE
Create 'condensed' design version

### ISSUE THREAD

**Issue by nlhkabu** [pypa/warehouse#1988]
We have had a lot of positive feedback about the new design. However, there are a number of power users who have made it clear that they prefer a more condensed, data-rich layout.

One possible solution is to have different viewing modes available - a bit like gmail:

![screenshot from 2017-05-13 22-03-41](https://cloud.githubusercontent.com/assets/3323703/26029215/0fffcc62-3828-11e7-86a3-00743cac5c73.png)

To start with we could have "Standard mode" and "compact mode".

Standard mode would display the current layout. Compact mode would significantly reduce the page whitespace.

On the CSS side, this would be a matter of adding a class to the body and changes each style accordingly.

@dstufft what do you think?  How could we do this on your side?

**Comment by dstufft** [comment]
I think the way of handling this in terms of implementation would be to have a separate cookie (that we filter out in the VCL so it doesn't affect caching) and implement the body class switching using javascript client side reading that cookie. If the user is logged in we can persist that setting server side using an ajax call to some internal endpoint and restore that persisted setting whenever the user logs in.

One thing I'd maybe push back on though is whether this is something that's worth spending time on. It seems like it's something that's going to increase the amount of effort of making any UI change since you're going to effectively need to design each change twice (or N times for each "mode") and since we don't have great UI level tests going, whatever the non-default mode is, is more likely to get broken unless we manually test each possible iteration.

To be clear, I'm not specifically against this, Mostly I'm questioning whether it's something we actually need. Is there in fact two distinct groups of users who need different UIs in order to effectively interact with the site, or can we satisfy both groups with a shared UI?

**Comment by nlhkabu** [comment]
Yes, I agree, it does significantly increase the workload.

> Is there in fact two distinct groups of users who need different UIs in order to effectively interact with the site, or can we satisfy both groups with a shared UI?

The only way to verify this is to do some direct user testing. I have a list of volunteers for this, but not a lot of time to conduct them. In the short term, let's see what feedback we get on this issue.

**Comment by rsyring** [comment]
FWIW, I think having two UIs is a waste of manpower.  One good UI should be sufficient IMO.  If the power users mentioned in the OP have convinced you that the current layout could be improved, then make those improvements.  If you aren't convinced, then leave the current layout.  But having two UI layouts to maintain/improve, just seems like a lot of work for very little benefit.

**Comment by nkanaev** [comment]
From my personal experience, I find npmjs.com [interface](https://www.npmjs.com/package/express) more appealing. They've managed to fit all the necessary information in one page without tab navigation, yet it doesn't feel bloated. Rubygems does the same [thing](https://rubygems.org/gems/rails), having the similar page structure.

What if we could borrow some of their ideas?

**Comment by anowlcalledjosh** [comment]
It seems like one obvious thing to do here would be to decrease the size of the header. Here's a side-by-side comparison of the above-the-fold view of npm, rubygems and Warehouse:

![image](https://user-images.githubusercontent.com/9433472/28647383-c6352174-725e-11e7-999b-18128268ae83.png)

Here's the same image, but with Warehouse scrolled so the header appears about the same size as the other two sites:

![image](https://user-images.githubusercontent.com/9433472/28647438-1b8c71c2-725f-11e7-960a-cc8f8297ca93.png)

A closeup of the scrolled Warehouse:

![image](https://user-images.githubusercontent.com/9433472/28647405-f0355570-725e-11e7-86ae-dab328aeb238.png)

That's massively better. And the only information lost in that change was the Warehouse logo, the package version, and the search bar\*, all of which would easily fit in the reduced header:

![image](https://user-images.githubusercontent.com/9433472/28647814-654411b0-7261-11e7-937d-54e8cdbd7961.png)

Alternatively:

![image](https://user-images.githubusercontent.com/9433472/28647806-5c093e9a-7261-11e7-9a62-b8118299b228.png)

(but then the install command starts to get a bit long, and runs the risk of crashing into the search bar.)

\*I'm not counting the donation banner, mostly because I forgot about it while I was making those mockups, and I'm too lazy to add it back in :) There's still space to fit some more text in, but it's not like a banner on the top would completely ruin how it looks.

**Comment by rsyring** [comment]
@anowlcalledjosh very helpful post, thanks.  FWIW, I think the first mockup you made is the best (package version by the date, simpler install command).  The only additional suggestion I'd make is that their should be a page heading with the package name and version, like NPM and rubygems.

**Comment by user-e** [comment]
Here's two screenshots comparing the two designs on a tablet screen. I describe some things that need improving in [this comment](https://github.com/pypa/warehouse/issues/2417#issuecomment-345027113).
Newer design that needs some improvements | Older design which had parts that look better
--- | ---
![screenshot_2017-11-16-17-40-21_kindlephoto-51496782](https://user-images.githubusercontent.com/13541254/32910161-67081fee-cb00-11e7-82ff-bf4b33d06a5c.png) | ![screenshot_2017-11-16-17-40-56_kindlephoto-51571735](https://user-images.githubusercontent.com/13541254/32910174-6f3cf4f0-cb00-11e7-9929-0f23fab3aae2.png)

Even though the new design looks okay shown here in portrait orientation, the whitespace and other things look worse in the horizontal screen size on my tablet device.

**Comment by JohnSpeno** [comment]
Yes, the current design seems to waste too much vertical space. The thing I care about 99% of the time when visiting a PyPI page is getting the link to it's github repo (or equivalent). That should be front and center to maximize my personal use case. Thanks.

**Comment by merwok** [comment]
Glad to see that this discussion is happening, and thanks for thinking about all aspects of the user experience.

FWIW the thing that made me search for this ticket was not individual project pages, but the search results: the rectangles with margins allow only four (with the big header) to six items on my screen, compared to around fifteen in the table on the old PyPI.

**Comment by di** [comment]
#3107 also echoes concerns about extra space on the search results page.

**Comment by brainwane** [comment]
I'm sorry for the delay in response here. The folks working on Warehouse have gotten [limited funding to concentrate on improving and deploying Warehouse](https://pyfound.blogspot.com/2017/11/the-psf-awarded-moss-grant-pypi.html), and have kicked off work towards [our development roadmap](https://wiki.python.org/psf/WarehouseRoadmap) -- the most urgent task is to improve Warehouse to the point where we can redirect pypi.python.org to pypi.org so the site is more sustainable and reliable. I'm the project manager for this effort and I've been in frequent consultation with our designer, Nicole Harris.

I think some of you have read Nicole's (@nlhkabu's) [writeup of her design goals, including her assessment of the legacy UI and its problems](http://whoisnicoleharris.com/2015/12/31/designing-warehouse-an-overview.html). She's [doing user tests to get more data on what users have trouble with](http://whoisnicoleharris.com/2018/03/13/user-testing-warehouse.html), and during those tests, looking at design inconsistency between www.python.org and Warehouse, usual device/browser/display usage and usual size/resolution, how much scrolling users have to do to achieve their goals, layout confusion, and so on. [She's opening issues based on that testing and tagging them "user testing"](https://github.com/pypa/warehouse/labels/user%20testing) in case you want to see what she's finding.

In the past several weeks we've also been fortunate enough to get volunteer frontend contributions from several folks (shoutout to @jMuzsik, @waseem18, @yeraydiazdiaz, @aalmazan, @jw, @Volcyy, @berkerpeksag, @alexwlchan, and @mds325, and sorry to anyone I forgot). I'd love input from any of you about how we could use existing functionality in Warehouse to give users the option of a more condensed experience, or what we could advise users to do to easily see a less styled, more condensed version immediately without code changes.

As Warehouse project manager, I'm marking this as something we will prioritize for post-launch work. I am sorry for the wait. We have limited grant-funded time to work on Warehouse and I am asking for volunteer help so we can get help on this issue faster.

**Comment by brainwane** [comment]
Noting here that some users [on python-list](https://mail.python.org/pipermail/python-list/2018-March/thread.html#732138) also expressed interest in a condensed view ([example](https://mail.python.org/pipermail/python-list/2018-March/732201.html)).

**Comment by brainwane** [comment]
I've broken out the request for _more search results on a result page_ into #3463, and am keeping here the request for a different search results layout to ease scrolling and visually comparing these results, as in https://github.com/pypa/warehouse/issues/1988#issuecomment-363653596 , #3107,  #1727, and recently [Ian Kelly on python-list](https://mail.python.org/pipermail/python-list/2018-March/732201.html).

**Comment by yeraydiazdiaz** [comment]
Having a look at the [newer NPM design](https://www.npmjs.com/package/react) and comparing it with [our currect one](https://pypi.org/project/Django/) I think we could benefit from using tabs and tables for the less important information and push upwards elements that are of more interest to the average user.

Here's a quick mockup rearranging some elements and adding tabs:

<img width="1285" alt="pypi-detail" src="https://user-images.githubusercontent.com/6739793/38193418-e6521096-3669-11e8-953b-0cc992e1a54c.png">

There's still quite bit of vertical space mainly taken by the classifiers, but I think it's more straight forward and compact this way.

**Comment by dstufft** [comment]
Homepage probably can't be a tab, because we can have an arbitrary number of links for a project of which Homepage is one. As far as the tabbed concept goes, I'll leave that up to @nlhkabu :)

**Comment by aklaver** [comment]
Is there any movement on this, as the below is not good. I realize many people are glued to a phone that show only one item at a time, but for those of us who are not and want to scan more information at a time the current layout is not working.

![screenshot_20180416_094241](https://user-images.githubusercontent.com/658260/38823229-aaf60484-415a-11e8-9a53-64d149c7f053.png)

**Comment by nlhkabu** [comment]
@Safihre, I am sorry that you thought I was not responding on this issue -- I have heard the feedback here and will be taking it into consideration for future design updates.

I'm the only designer on this project and I'm working about ~10 hours a week, focusing on immediate launch-related issues. Often, when coding, reviewing others' PRs, user testing, and training others to user test takes up nearly all of my ~10 hours/week on Warehouse, I'm not going to have time to respond as fast as users would like to open issues (even issues I opened, like this one), and @brainwane will be replying in my stead (as she has done on many other tickets). I recognise that isn't ideal, and that this is an issue that several people have spoken about, however I need to prioritise my time to address those tickets which are blocking the team moving forward on our roadmap.

We need to user test this -- along with several other issues (marked "user test") to quantify how many people have this preference and balance that against what other users prefer. After this, we can start making decisions about what updates to make, and when.

**Comment by aklaver** [comment]
I believe, since there are issues going back to November 2015 related to this, that the user testing has been done and the site has been found wanting. Also AFAICT the roadmap for the new site is done:

**Comment by brainwane** [comment]
@yeraydiazdiaz I'd like for you to turn your mockup from https://github.com/pypa/warehouse/issues/1988#issuecomment-377904285 into a PR or a demo that @nlhkabu can use in user testing. Could you do that?

**Comment by gvanrossum** [comment]
Whatever you do, please don't create a choice for the user between spread out and compact. That's a solution for lazy designers. Focus on usability. Also, think about who your users are and what they want. People don't go to pypi.org thinking "today I'm gonna download me some software". They come there with specific needs. Find those needs and the rest will follow.

**Comment by brainwane** [comment]
@gvanrossum Thanks for your comment.

We do recognize that people come to PyPI with specific needs and tasks in mind; I recommend you check out [Nicole's initial post](http://whoisnicoleharris.com/2015/12/31/designing-warehouse-an-overview.html) and [the user testing overview](http://whoisnicoleharris.com/2018/03/13/user-testing-warehouse.html) for more on how we discover those needs and test how PyPI fulfills, or doesn't fulfill, them. I do believe that, right now, we are leaning strongly towards making one UI rather than a spread out versus compact user option.

Please don't insinuate that our designer would be lazy. I recognize that a lot of us have dealt with hard-to-use designs in the past (including ones that make software harder to maintain because of combinatoric explosions), but let's distinguish between laziness in solutions and personal attributes of our contributors.

Thanks for the guidance.

**Comment by aklaver** [comment]
@brainwane the issue is that pypi is a utility site where people go to search and find information, possibility large amounts of information.  Having to scroll through pages bloated with empty space makes the process painful. While I empathize with the current time and financial crunch, the topic under discussion has been know for some time(#793) and as the screenshot from the issue shows has not been dealt with in any meaningful manner.

**Comment by anowlcalledjosh** [comment]
If anyone wants a nicer workaround than turning off styles completely, I've hacked up a user stylesheet (which you can use with something like [Stylus](https://add0n.com/stylus.html)) to condense PyPI a bit; it's not perfect, and I'm not intending this as a suggestion for what I think PyPI should look like, but I do think it improves things somewhat.

<details><summary>Stylesheet</summary>

```css
@-moz-document domain("pypi.org") {
/* header */

.site-header__logo {
    /* down from 15px */
    padding-top: 8px;
    padding-bottom: 8px;
}

.horizontal-menu--tall .horizontal-menu__link {
    /* down from 32px */
    padding-top: 25px;
    padding-bottom: 25px;
}

.search-form--primary {
    margin-top: 17px;
}

/* footer */

.footer__menus {
    margin-bottom: 0px; /* from 30px */
}

.footer {
    /* down from 30px */
    padding-top: 30px;
    padding-bottom: 20px;
}

/* homepage */

.homepage-banner__title { /* "Find, install and publish Python packages with the Python Package Index" */
    /* down from 40px */
    padding-bottom: 10px;
    /*display: none;*/ /* uncomment if you really want, I guess */
}

.homepage-banner__browse {
    /* down from 30px */
    margin-top: 10px;
}

.statistics-bar__statistic {
    /* down from 10px */
    padding-top: 0;
    padding-bottom: 0;
}

.banner {
    /* down from 50px */
    padding-top: 8px;
    padding-bottom: 8px;
}

.package-snippet {
    /* down from 15px */
    padding-top: 5px;
    padding-bottom: 5px;
    min-height: 65px; /* make the cards line up when a description is missing */
}

.horizontal-section {
    /* down from 70px */
    padding-top: 20px;
    padding-bottom: 20px;
}

.horizontal-section--thin {
    /* down from 10px */
    padding-top: 4px;
    padding-bottom: 4px;
}

.horizontal-section--statistics {
    padding-top: 10px;
    padding-bottom: 10px;
}

/* package details */

.package-header__name {
    margin-top: 0;
    margin-bottom: -10px;
}

.package-header__pip-instructions {
    /* I tried to get this to display in the header, but couldn't -- display: inline-block is probably the way forward */
    display: none;
}

.package-header__date {
    display: inline;
    margin-left: 0.5em;
}

.package-header__right {
    width: -webkit-fill-available;
    width: 40%;
}

.vertical-tabs__tab:focus { /* workaround for irritating bug where focused tab flashes on mouseover */
    background: #006dad;
    color: #fff;
}

.sidebar-section {
    /* from 20px */
    padding-bottom: 10px;
    margin-bottom: 10px;
}

.vertical-tabs__tab {
    /* from 15px -- changed for symmetry with section dividers */
    padding-top: 10px;
    padding-bottom: 10px;
}

#description .page-title {
    /* down from 30px */
    padding-bottom: 0px;
}

.project-description * {
    /* down from 30px */
    margin-top: 10px !important;
}

/* account settings */

hr {
    /* down from 45px */
    margin-top: 20px;
    margin-bottom: 20px;
}

/* releases */

.release__card {
    /* down from 15px */
    margin-top: 5px;
    margin-bottom: 5px;
}
}
```

</details>

<details><summary>Screenshots</summary>

![pypi-stylesheet](https://user-images.githubusercontent.com/9433472/38948013-4e67a816-4336-11e8-9742-3f8b3bb049c0.png)

</details>
