### ISSUE TITLE
Allow specifying README translations

### ISSUE THREAD

**Issue by verhovsky** [pypa/warehouse#9243]
**What's the problem this feature will solve?**

Some projects have their READMEs translated to other languages, such as https://github.com/willmcgugan/rich . If people care enough to write these translations, there's probably people that would care to see them on PyPI as well.

**Describe the solution you'd like**

We have to maintain the `readme = ` option for backwards compatibility and because the shorthand is convenient and having one README as the default fallback is good too. So something like

```toml
readme = "README.md"
readme-translations = {en = "README.md", zh = "README.zh.md" }  # readme-lang? readme-languages?
```

Ideally it would support arbitrary BCP47 language tags (e.g. `en_US` and `zh_CN_Hans`), but maybe that's overkill. Pypi could decide which version to show based on either the browser's `accept-language` header but a way to overwrite that would be nice, because the browser's language is not always configured correctly. So you should be able to specify which languages you speak either on your user page or in a drop down on the page displaying the README.
